@Library("Shared") _

pipeline {
    agent {
        docker {
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        SONAR_URL = "localhost:9000"
        LOCATION = "java-maven-sonar-argocd-helm-k8s/spring-boot-app"
        DOCKER_IMAGE= "maven-cicd"
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    github_clone(
                        "https://github.com/abhradippaul/Jenkins-Zero-To-Hero.git", "main", "")
                }
            }
        }
        stage('Build and Test') {
            steps {
                sh "cd ${LOCATION} && mvn clean package"
            }
        }
        stage('Static Code Analysis') {
            steps {
                script {
                    maven_sonar_test(
                    "sonar-scanner", 
                    "${LOCATION}", 
                    "${SONAR_URL}")
                }
            }
        }
        stage("Build and Push Docker Image") {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: "dockerhub-jenkins",
                    usernameVariable: "username", 
                    passwordVariable: "password")]) {
                        sh "docker login -u ${username} -p ${password}"
                        sh "cd ${LOCATION} && \
                        docker build -t ${username}/${DOCKER_IMAGE}"
                        sh "docker push ${username}/${DOCKER_IMAGE}"
                    }
            }
        }
    }
}