@Library("Shared") _

pipeline {
    agent {
        docker {
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    github_clone(
                        "https://github.com/abhradippaul/Jenkins-Zero-To-Hero.git", "main", "")
                }
            }
        }
    }
}