apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-app
    app.kubernetes.io/instance: test
  name: spring-boot-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-app
status:
  loadBalancer: {}
