pipeline {
    agent {label 'master'}
    // agent {
    //     docker {
    //         image 'node:current-alpine3.22'
    //         args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
    //     }
    // }
    
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        DOCKER_IMAGE = 'nodejs-devsecops'
        LOCATION = "npm_devsecops/app/frontend"
    }

    stages {

        stage('clean workspace'){
            steps{
                cleanWs()
            }
        }

        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/abhradippaul/Jenkins-Projects.git'
                echo "Git Checkout completed successfully."
            }
        }

        // stage('Sonarqube Analysis'){
        //     steps {
        //         withSonarQubeEnv('sonar-scanner') {
        //             sh ''' $SCANNER_HOME/bin/sonar-scanner \
        //             -Dsonar.projectName=React-Frontend \
        //             -Dsonar.projectKey=React-Frontend \
        //             -Dsonar.sources=$LOCATION '''
        //         }
        //         echo 'SonarQube Analysis Completed'
        //     }
        // }

        // stage("Quality Gate") {
        //     steps {
        //         script {
        //             def qg = waitForQualityGate()
        //             if (qg.status != 'OK') {
        //                 error "Pipeline aborted due to quality gate failure: ${qg.status}"
        //             }
        //             echo "Quality gate passed successfully"
        //         }
        //     }
        // }

        stage('Install Dependecy') {
            steps {
                sh "cd $LOCATION && npm install"
                echo 'File System Scan Completed'
            }
        }

        stage('File System Scan') {
            steps {
                sh "trivy fs --format table -o /data/fs/BoardGame.html ."
                echo 'File System Scan Completed'
            }
        }

        stage('OWASP Dependency-Check Vulnerabilities') {
            steps {
                dependencyCheck additionalArguments: ''' 
                            -o './'
                            -s './$LOCATION'
                            -f 'ALL' 
                            --prettyPrint''', odcInstallation: 'owasp'
                
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
            }
        }

        stage('Login to DockerHub and Build Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh "rm -rf $LOCATION/node_modules"
                    sh "docker build -t ${username}/${DOCKER_IMAGE}:${params.BUILD_NUMBER} $LOCATION/"
                    sh "docker login -u ${username} -p ${password}"
                }
                echo "Docker Image build and Docker Hub login completed."
            }
        }

        stage('Scan Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh "trivy image --format json --output /data/image/BoardGame.json ${username}/${DOCKER_IMAGE}:${params.BUILD_NUMBER}"
                }
                echo "Scan Docker Image completed."
            }
        }
        
        stage('Publish to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh "docker push ${username}/${DOCKER_IMAGE}:${params.BUILD_NUMBER}"
                }
                echo "Publish to Docker Hub is completed."
            }
        }

        stage('Push changeed yaml') {
            steps {
                sh "sed -i 's/^  tag: .*/  tag: ${params.BUILD_NUMBER}/' npm_devsecops/manifest/values.yaml"
                sh "cat npm_devsecops/manifest/values.yaml"
                // sh "git add java_devsecops/maven-app-chart/values.yaml"
                // sh "git commit -m 'Change yaml deployment image tag to ${params.BUILD_NUMBER}'"
                // withCredentials([gitUsernamePassword(credentialsId: 'your-git-credentials-id', gitToolName: 'Default')]){
                //     sh "git push --set-upstream origin main"
                // }
                echo "Yaml file changes successfully"
            }
        }

    }
}
