pipeline {
    agent {label 'master'}
    
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        DOCKER_IMAGE = 'nodejs-devsecops'
        LOCATION = "npm_devsecops/app/frontend"
    }

    stages {

        stage('clean workspace'){
            steps{
                cleanWs()
            }
        }

        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/abhradippaul/Jenkins-Projects.git'
                echo "Git Checkout completed successfully."
            }
        }

        // stage('Sonarqube Analysis'){
        //     steps {
        //         withSonarQubeEnv('sonar-scanner') {
        //             sh ''' $SCANNER_HOME/bin/sonar-scanner \
        //             -Dsonar.projectName=React-Frontend \
        //             -Dsonar.projectKey=React-Frontend \
        //             -Dsonar.sources=$LOCATION '''
        //         }
        //         echo 'SonarQube Analysis Completed'
        //     }
        // }

        // stage("Quality Gate") {
        //     steps {
        //         script {
        //             def qg = waitForQualityGate()
        //             if (qg.status != 'OK') {
        //                 error "Pipeline aborted due to quality gate failure: ${qg.status}"
        //             }
        //             echo "Quality gate passed successfully"
        //         }
        //     }
        // }

        stage('Install Dependecy') {
            steps {
                sh "cd $LOCATION && npm install"
                echo 'File System Scan Completed'
            }
        }

        stage('File System Scan') {
            steps {
                sh "trivy fs --format table -o ./BoardGamefs.html ."
                sh "cp BoardGamefs.html /data/fs/BoardGamefs.html"
                echo 'File System Scan Completed'
            }
        }

        stage('OWASP Dependency-Check Vulnerabilities') {
            steps {
                dependencyCheck additionalArguments: ''' 
                            -o './'
                            -s './$LOCATION'
                            -f 'ALL' 
                            --prettyPrint''', odcInstallation: 'owasp'
                
                dependencyCheckPublisher pattern: 'dependency-check-report.xml'

                echo "Dependency scan successfully completed"
            }
        }

        stage('Login to DockerHub and Build Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh "rm -rf $LOCATION/node_modules"
                    sh "docker build -t ${username}/${DOCKER_IMAGE}:${params.BUILD_NUMBER} $LOCATION/"
                    sh "docker login -u ${username} -p ${password}"
                }
                echo "Docker Image build and Docker Hub login completed."
            }
        }

        stage('Scan Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh "trivy image --format table -o BoardGameimage.html ${username}/${DOCKER_IMAGE}:${params.BUILD_NUMBER}"
                    sh "cp BoardGameimage.html /data/image/BoardGameimage.html"
                }
                echo "Scan Docker Image completed."
            }
        }
        
        stage('Publish to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'jenkins-docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh "docker push ${username}/${DOCKER_IMAGE}:${params.BUILD_NUMBER}"
                }
                echo "Publish to Docker Hub is completed."
            }
        }

        stage('Push changeed yaml') {
            steps {
                sh "sed -i 's/^  tag: .*/  tag: ${params.BUILD_NUMBER}/' npm_devsecops/manifest/values.yaml"
                sh "cat npm_devsecops/manifest/values.yaml"
                sh "git add npm_devsecops/manifest/values.yaml"
                sh "git commit -m 'Change yaml deployment image tag to ${params.BUILD_NUMBER}'"
                withCredentials([gitUsernamePassword(credentialsId: 'git-credentials-id', gitToolName: 'Default')]){
                    sh "git push --set-upstream origin main"
                }
                echo "Yaml file changes successfully"
            }
        }


    }

    post {
        always {
            emailext attachLog: true,
            body: "Project: ${env.JOB_NAME}<br/>" +
                "Build Number: ${env.BUILD_NUMBER}<br/>" +
                "URL: ${env.BUILD_URL}<br/>",
            to: 'abhradipserampore@gmail.com',     
            attachmentsPattern: 'BoardGamefs.html,BoardGameimage.html,dependency-check-report.html',
            subject: "'${currentBuild.result} ${DOCKER_IMAGE} ${env.BUILD_NUMBER}'"
        }
    }
}
